

function LoadLanguage(Language) {
    localStorage.removeItem('LoadLabelsByLanguage');

    if (Language == 'English') {
        localStorage.setItem('LoadLabelsByLanguage', JSON.stringify({
            ToDO: 'To do',
            Message: 'Message',
            Appointment: 'Appointment',
            Appointdashment: 'Appoint-ment',
            Appointments: 'Appointments',
            ContactSearch: 'Contact Search',
            Accounts: 'Accounts',
            Proposals: 'Proposals',
            Contacts: 'Contacts',
            Deal: 'Deal',
            Tasks: 'Tasks',
            TaskType: 'Task',
            OpentaskList: 'Open Task List',
            Proposallist: 'Proposal List',
            Importphonecontacts: 'Import your Phone Contacts',
            ImportGooglecontacts: 'Import Google Contacts',
            GoogleCalendarSync: 'Google Calendar Sync',
            GoogleTasksync: 'Google Task Sync',
            Settings: 'Settings',
            MyProfile: 'My <br/>Profile',
            Tutorial: 'Tutorial',
            Overview: 'Overview',
            Rateandreview: 'Rate and review',
            Privacy: 'Privacy',
            Hot: 'Hot deal',
            Lead: 'Sales lead',
            Warm: 'Warm deal',
            Investigation: 'Investigation',
            Presentation: 'Presentation',
            Prospect: 'Prospect',
            Forecast: 'Forecast',
            Funnel: 'Funnel',
            Opportunity: 'Opportunity',
            Wonthismonth: 'Won this month',
            Newfunnelthismonth: 'New funnel this month',
            Search: 'Search',
            Detail: 'Detail',
            Dashboard: 'Dashboard',
            DealHeaderLabelDecisionmaker: 'Decision Maker',
            Message: 'Message',
            Messages: 'Messages',
            AccountName: 'Account Name',
            ContactName: 'Contact Name',
            ForeCastDate: 'Forecast Date',
            Chance: 'Chance',
            ProductCategory: 'Product',
            ProductName: 'Product Name',
            BudgetValue: 'Budget Value',
            BudgetStage: 'Budget Stage',
            SolutionPresented: 'Solution Presented',
            Comments: 'Comments',
            Comment: 'Comment',
            Budget: 'Budget',
            Authority: 'Authority',
            Need: 'Need',
            Time: 'Time',
            TimeFrom: 'Time From',
            TimeTo: 'Time To',
            Learning: 'Learning',
            Quotevalue: 'Quote value',
            Quotedate: 'Quote date',
            Quotevsbudget: 'Quote vs budget',
            Address1: 'Address 1',
            Address2: 'Address 2',
            City: 'City ',
            State: 'State',
            Country: 'Country',
            PostalCode: 'Postal Code',
            Website: 'WebSite',
            Industry: 'Industry',
            FirstName: 'First Name',
            LastName: 'Last Name',
            Email: 'Email',
            Mobile: 'Mobile',
            Designation: 'Designation',
            Contacts: 'Contacts',
            Activities: 'Activities',
            Tasks: 'Tasks',
            ShortAccountName: 'Short Account Name',
            Password: 'Password',
            AllContact: 'All Contacts',
            AllAccount: 'All Accounts',
            ProposalName: 'Proposal Name',
            Subject: 'Subject',
            Status: 'Status',
            FollowUpDate: 'Follow-Up Date',
            PendingSince: 'Pending Since',
            DealValue: 'Deal Value',
            Place: 'Place',
            PhoneContacts: 'Phone Contacts',
            SendProposal: 'Send Proposal',
            SendMail: 'Send Mail',
            DecisionMaker: 'Decision Maker',
            YoumustfillName: 'You must fill Name.',
            YoumustfillAccountName: 'You must fill the Account Name.',
            YoumustfillStateOrCity: 'You must fill either State Or City.',
            AccountSaveSuccessfully: 'Account Saved Successfully.',
            ContactSaveSuccessfully: 'Contact Saved Successfully',
            AddNewAccount: 'Add New Account',
            AddNewContact: 'Add New Contact',
            AddNewTask: 'Add New Task',
            AddNewDeal: 'Add New Deal',
            YoumustfillFirstNameorLastName: 'You must fill First Name or Last Name.',
            TryallFeatursofSaleshwahCRMfor30days: 'Try Saleshwah CRM for 30 days',
            KeepitfreeforeverandyourdataontheBasicPlan: 'Keep it free forever on the Basic Plan.',
            IfyourbusinessissellingtootherbusinessesyougottogetSaleswahCRM: 'If your business is selling to other businesses, you got to get Saleswah CRM',
            YoumustfillEmailorMobile: 'You must fill Email or Mobile',
            Invalidemailaddress: 'Invalid email address',
            SorryYouhavenotenteredaccountname: 'Sorry! You have not entered Account Name',
            SignIn: 'Sign In',
            SigninwithFacebook: 'Sign in with Facebook',
            SigninwithGoogle: 'Sign in with Google',
            SigninwithLinkedin: 'Sign in with Linkedin',
            SigninwithMicrosoft: 'Sign in with Microsoft',
            SorryYouHaveNotSelectTask: 'Please select a Task.',
            SorryYouHaveNotSelectContact: 'Please select a Contact',
            TargetDateMustBeGreaterThenCurrentDate: 'Target date must be greater then or equal to current date.',
            FollowupdatemustbeGreaterThenCurrentDate: 'Followupdate must be greater then or equal to current date.',
            TaskCreatedSuccessfully: 'Task created Successfully',
            TaskSaveSuccessfully: 'Task saved successfully',
            Updated: 'Updated',
            NotUpdated: 'Not updated',
            Saved: 'Saved',
            AccountNameDoesnotExists: 'Account name does not exist.',
            TargetnameMustBeGreaterThanAndEqualToCurrentDate: 'Target Date must be greater than or equal to current date.',
            ForeCastDateMustBeGreaterThanAndEqualToCurrentDate: 'Forecast Date must be greater than or equal to current date.',
            PleaseSelectProductCategory: 'Please Select Product Category',
            //Lead: 'Lead',
            PleaseEnterTitle: 'Please Enter Title',
            PleaseEnterPlace: 'Please Enter Place',
            FrmToDateNotLessCurrentDate: 'Appointment From date not less than current date',
            FrmDateNeverLessthemToDate: 'Appointment To date not less than current date',
            Guest: 'Guests',
            AddNewGuest: 'Contact/ Email:',
            PleaseAddAtLeastOneGuest: 'Please add at least one guest',
            AppointmentCreatedSuccessfully: 'Appointment created successfully',
            AppointmentNotCreated: 'Appointment not created',
            PendingTask: 'Pending Task',
            LiveDeals: 'Live Deals',
            WonDeals: 'Won Deals',
            LostDeals: 'Lost Deals',
            ProposalNumber: 'Proposal Number',
            QuotsNumber: 'Quotes Number',
            LastActivity: 'Last Activity',
            NextMetting: 'Next Meeting',
            Contactdeleted: 'Contact deleted',
            Accountdeleted: 'Account deleted',
            Contactisalreadyadded: 'Contact is already added',
            AccountNotSaveSuccessfully: 'Account Not Saved',
            ContactSaveSuccessfully: 'Contact saved successfully',
            ContactNotSaveSuccessfully: 'Contact not saved',
            DealStatus: 'Deal Status',
            ProfileUpdated: 'Profile Updated',
            Name: 'Name',
            Manager: 'Manager',
            Role: 'Role',
            CompanyName: 'Company Name',
            SMTPServer: 'SMTP Server Name',
            PortNumber: 'Port Number',
            EnableSSL: 'EnableSSL',
            Description: 'Description',
            Descripdashtion: 'Descrip-tion',
            UploadProduct: 'Upload Product',
            ChangePassword: 'Change Password',
            CompanyProfile: 'Company <br/>Profile',
            EmailSetup: 'Email <br/>Setup',
            CompanydetailsUpdated: 'Company details Updated',
            YoumustfillEmailAddress: 'You must fill Email Address',
            YoumustfillPassword: 'You must fill Password',
            YoumustfillPortNo: 'You must fill Port No.',
            YoumustfillSMTPServerName: 'You must fill SMTP Server Name.',
            SMTPSettingsUpdated: 'SMTP settings updated.',
            NewtaskSeedinserted: 'New task created',
            TaskDescriptionCantBeEmpty: 'Task description can not be empty',
            OldPassword: 'Old Password',
            NewPassword: 'New Password',
            ConfirmPassword: 'Confirm Password',
            Youmustfill_OldPassword: 'You must fill old password',
            Youmustfill_NewPassword: 'You must fill new Password',
            Youmustfill_ConfirmPassword: 'You must confirm Password',
            NewPasswordAndOldPasswordSame: 'New password and old password can not be same',
            ConfirmPasswordAndNewPasswordMustBeSame: 'New password and confirm password must be same',
            Passwordupdated: 'Password updated.',
            passwordNotUpdated: 'Password not changed',
            UpdateMasterTaskType: 'Master task updated',
            PleaseSelectTaskStatus: 'Sorry! You have not selected task status.',
            PleaseselectRoleofDecisionMaker: 'Please select role of decision makers.',
            PleaseSelectContactToAddAsADecisionMaker: 'Please select contact to add as a decisionmaker',
            DecisionMakerSaveSuccessfully: 'Decision Maker(s) added to Deal.',
            DecisionMakerNotSaveSuccessfully: 'Decision Maker not saved',
            AddNewContact: 'Add Contact',
            AddNewAccount: 'Add Account',
            AddNewTask: 'Add Task',
            AddNewDeal: 'Add Deal',
            AddNewAppointment: 'Add Appointment',
            AddNewPhoneContact: 'Add PhoneContact',
            ContactList: 'Contact List',
            DealList: 'Deal List',
            AccountList: 'Account List',
            TaskList: 'Task List',
            AppointmentList: 'Appointment List',
            ActivityList: 'Activity List',
            MessageList: 'Message List',
            //ForgetPasswordCreateAccount: 'Forgot password?  |  Create an account',
            Copyrighttext: '(c) Copyright Anwesha CRM Pvt Ltd.',
            Termsandcondition: 'Terms and Conditions',
            Privacy: 'Privacy',
            Forgetpassword: 'Forgot password?',
            Createanaccount: 'Create an account',
            DecisionMakerRoleUpdated: 'Decision Maker Role updated.',
            AddDecisionMaker: 'Add decision makers',
            YouMustFillYourFullName: 'You must fill your full name',
            YouMustFillYourCompanyName: 'You must fill your Company name',
            PleaseSelectYourCountry: 'Please select your country',
            GetStarted: 'Get Started',
            WelcomeScreenHeader: 'Welcome',
            WelcomeToSaleswah: 'Welcome to Saleswah',
            YouCanUseSaleswahOnYourPhone: 'You can use Saleswah on your phone- Android/ Windows/ iPhone, on the weband on the Windows 8 desktop. The same credentials work everywhere.',
            YourShortAccountNameIs: 'Your short account name is',
            YourregisteredEmailidIs: 'Your registered email id is',
            Pleasechangeyourpasswordnow: 'Please change your password now',
            YourRole: 'your Role',
            YourLicense: 'Your license',
            validtill: 'valid till',
            WhatYouCanDo: 'What you can do',
            CreateUnlimitedContacts: ' Create unlimited Contacts, Accounts, Deals, Tasks, Proposals, Quotes, Campaigns till your license is valid. After the end of your free trial, you can continue to use Saleswah but some functionalities will be restricted/ withdrawn.',
            YourdataStaysSafeAndSecure: 'Your data stays safe and secure till you request us to delete your account.',
            Upgradingtoapaidaccount: 'Upgrading to a paid account has benefits- including being able to add other colleagues and collaborate in a team.',
            WhileyoucanstartusingSaleswahrightnow: 'While you can start using Saleswah right now, a little set up will help you get the best of Saleswah.',
            DecisionMakerremovedfromDeal: 'Decision Maker(s) removed from Deal.',
            PleaseChangeyourPasswordFirst: '*please change your password first',
            OkGotIt: 'Ok Got it',
            Selectcontacttosend: 'Sorry! You have not select contact to send.',
            Proposalsendsuccessfully: 'Proposal send successfully.',
            Proposalsendingfail: 'Proposal sending fail.',
            TypeHereToSearch: 'Type here to search',
            TypeHereToSearchContact: 'Type here to search contact',
            TypeHereToSearchContactEmail: 'Type here to search contact/email',
            TypeHereToSearchAccount: 'Type here to search account',
            RegisterBacktoSignin: 'Back to Sign In',
            RegistertxtFullName: 'Full Name',
            RegistertxtCompanyName: 'Company Name',
            RegistertxtEmailAddress: 'Email Address',
            PleaseGoToOurWebsiteToUploadProduct: 'Please goto web upload products (https://crm.saleswah.com).',
            YoumustfillEamilAddress: 'Sorry! You have not entered email address.',
            YoumustfillShortAccountName: 'Sorry! You have not entered short account name.',
            YoumustfillPassword: 'Sorry! You have not entered password.',
            Verify: 'Verify',
            PleaselinkyourexistingSaleswahaccount: 'Please link your existing saleswah account',
            PleaseCheckyourInternetConnection: 'Please check your internet connection',
            NoTaskToDoForToday: 'No Task for today',
            PleaseSelectIndustry: 'please select industry',
            PleaseSelectForeCastDate: 'please select forecast date',
            PleaseCheckYourEmailShortAccountNameAndPassword: 'Please check your email, short account name & password',
            AvailableOnlytoAdministrator: 'Available only to administrator',
            logout: 'Logout',
            UserName: 'UserName',
            FromDatenotGreaterThanToDate: 'FROM date can not be greater than TO date',
            SendmeNewPassword: 'Send me new password',
            shortaccountnameisnotvalid: 'Sorry! short account name is not valid.',
            Eitheruserwiththisemailnotexist: '1.Either user with this email not exist or <br/>2. Incorrect mail settings',
            PasswordchangedsuccessfullyPleasecheckyouremail: 'Password changed successfully. Please check your email at :',
            AccountDeleteConfirmMessage: 'Are you sure to delete account?',
            ContactDeleteConfirmMessage: 'Are you sure to delete contact?',
            DeleteAccountPopUpTitle: 'Delete Account',
            DeleteContactPopUpTitle: 'Delete Contact',
            ContactAlreadyExists: 'Same name & email contact already exists in this account.',
            PhoneContact_ImpConfrm: 'Want to import your phone contacts into Saleswah? Click OK to start.',
            ImportphoneContact: 'Import Phone Contact',
            PhoneContact_TotalFound: 'Total contacts found in your phone.',
            PhoneContact_TotalReadyToImp: 'Total contacts ready for import',
            PhoneContact_NotReadyToImp: 'contacts found ready for import',
            PhoneContact_TotalImported: 'contacts identified from phone. Check your contact list for phone contacts and select the ones for final import.',
            PleaseUpdateContactPhoneNumber:'Please Update Contact Mobile Number',
            ActivityName:'Activity Name',
            RelatedTo:'Related To',
            ActivityDate:'Activity Date',
            ActivityDetails:'Activity Details',
            SorryYouHaveSelectedTheWrongTask:'Sorry you have selected the wrong task',
            SorryYouHaveSelectedTheWrongDeal: 'Sorry you have selected the wrong Deal',
            ActivityInsertedSuccessfully:'Activity Created Successfully',
            TaslOrDeal:'Task/Deal',
            Activity:'Activity',
            DoYouWantToLogThisCallasActivity:'Do you want to log this call as activity! against(Deal/Task)?',
            Alert:'Alert'
        }))
    }
    else
        if (Language == 'Hindi') {

        }
}